Feature/about main
viktoriiahdev/team-project-ice-cream pull request #29
Opened 2022-04-02 17:45 UTC by LeonidGarasko

mobile-first

2022-04-02 18:32 UTC, viktoriiahdev requested changes
Треба трошки підправити

2022-04-02 18:32 UTC, viktoriiahdev commented on src/sass/layout/_about.scss
>      justify-content: center;
Додай `gap: 30px`
для мобільних `40px`

2022-04-02 18:32 UTC, viktoriiahdev commented on src/sass/layout/_about.scss
> +  }
Оці стилі не потрібні, тут ширина обмежується контейнером
```
max-width: 280px;
```
та 
```
@media screen and (min-width: $medium) {
     max-width: 336px;
 }
```


Отут замість `margin-bottom` буде `gap`
```
@media screen and (max-width: 767px) {
     margin-bottom: 40px;
 }
```

2022-04-02 18:32 UTC, viktoriiahdev commented on src/sass/layout/_about.scss
>    max-width: 220px;
Тут треба теж прибрать `max-width`, як обмежимо ширину написала нижче

2022-04-02 18:32 UTC, viktoriiahdev commented on src/sass/layout/_about.scss
>    max-width: 220px;
Треба додать 
```
.about__text--wraper{
   flex: 1;
}
```

і для `picture` (або `about__image`) 
```
{
   flex: 1;
}
```

для тощо, щоб вони займали однакову ширину батьківського контейнера

2022-04-02 18:32 UTC, viktoriiahdev commented on src/partials/about.html
>          <button class="button button--main button--large" type="button">Read more</button>
додай `svg #chevron-right` в кнопку 
```
  <svg class="icon button__icon button__icon--append">
    <use href=""></use>
  </svg>
```

2022-04-02 18:32 UTC, viktoriiahdev commented on src/sass/layout/_about.scss
> +  background-image: url(../images/milk-wave_320.png);
додать `image-set` для різних екранів

2022-04-03 09:58 UTC, LeonidGarasko commented on src/partials/about.html
>          <button class="button button--main button--large" type="button">Read more</button>
добавил

2022-04-03 09:58 UTC, LeonidGarasko commented on src/sass/layout/_about.scss
> +  background-image: url(../images/milk-wave_320.png);
Сделал

2022-04-03 09:58 UTC, LeonidGarasko commented on src/sass/layout/_about.scss
>    max-width: 220px;
Пока маржины , если решим что не принципиально - сделаю одинаково

2022-04-03 09:58 UTC, LeonidGarasko commented on src/sass/layout/_about.scss
> +  }
Сделал

2022-04-03 09:59 UTC, LeonidGarasko commented on src/sass/layout/_about.scss
>      justify-content: center;
+

2022-04-03 14:12 UTC, viktoriiahdev approved these changes

2022-04-03 14:13 UTC, merged