Feature/review
viktoriiahdev/team-project-ice-cream pull request #39
Opened 2022-04-03 21:25 UTC by EvgeniyTIR

Намучался я с этим слайдером ^^. Застрял на таком варианте, с костылями , как по другому сделать идеально по макету пока не придумал)

2022-04-03 22:21 UTC, viktoriiahdev requested changes
Гарна робота зі слайдером👌🏻
Залишила купку коментарів, чекаю на зміни 😉

2022-04-03 22:21 UTC, viktoriiahdev commented on src/partials/reviews.html
> +     </div>
- `class="reviews-slider__img"` замінить на  `review__img`
- `reviews-slider__text-wrap` на `review__text-wrap`
- `reviews-slider__text` на `review__text`
- `reviews-slider__name` на `review__author`

- `reviews__item--dots` по-моєму казали робити псевдоелементом з `svg`
можна зробить як `.review:after`

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +.reviews{
виправить всі класи відповідно до html

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +    border-radius: 44px;
Для круглого зображення треба задавати `border-radius: 50%;`

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +   background-image: -webkit-repeating-linear-gradient(top, transparent 0px, transparent 29px, #E1E1E1 31px, transparent 20px);
Бачу префікси, якщо у вас досі включений `live sass compiler`, виключте - бо він може призводить до конфліктів, його повністю заміняє `npm run dev`

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +   margin-left: 10px;
Щр це за дивно заданий стиль такий?

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +.slick-dots li button:before{
селектор замінить на `.slick-dots button:before`

2022-04-03 22:21 UTC, viktoriiahdev commented on src/sass/layout/_reviews.scss
> +    height: 12px;
Іонка доміка має бути не на активному слайді, а на першому, тобто для `.slick-dots:fist-child`

2022-04-04 09:08 UTC, EvgeniyTIR commented on src/index.html
> +    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
були помилки, намагався підключити локально

2022-04-04 09:11 UTC, EvgeniyTIR commented on src/partials/reviews.html
> +    <div class="reviews-slider">
тут не зрозумів трохи, додати до multiple-items?

2022-04-04 09:13 UTC, EvgeniyTIR commented on src/sass/layout/_reviews.scss
> +   margin-left: 10px;
відступи для крапок

2022-04-04 10:49 UTC, EvgeniyTIR commented on src/sass/layout/_reviews.scss
> +   background-image: -webkit-repeating-linear-gradient(top, transparent 0px, transparent 29px, #E1E1E1 31px, transparent 20px);
live sass виключиний, без префіксів чомусь не працює

2022-04-04 11:17 UTC, EvgeniyTIR commented on src/sass/layout/_reviews.scss
> +    height: 12px;
як на мене, то дивно якщо вона статична, але ок)

2022-04-05 08:31 UTC, viktoriiahdev requested changes
Чекаю правки, про які написала в Слак

2022-04-05 18:47 UTC, viktoriiahdev commented
залив на іншу гілку

2022-04-05 18:47 UTC, closed without merging