Feature/products modal
viktoriiahdev/team-project-ice-cream pull request #82
Opened 2022-04-10 08:52 UTC by AnnaKhanina

Не получилось сделать border-radius для picture

2022-04-10 12:53 UTC, viktoriiahdev requested changes

2022-04-10 12:53 UTC, viktoriiahdev commented on src/sass/layout/_products.scss
> +    transition: transform box-shadow 250ms $cubic;
отак не можна записувати, для `transform` треба записати `250ms $cubic` окремо, і для `box-shadow` теж окремо, має бути отак
`transition: transform 250ms $cubic, box-shadow 250ms $cubic;`

або можна отак записувати
```
transition-property: transform, box-shadow;
transition-duration: 250ms;
transition-timing-function: $cubic;
```

2022-04-10 13:02 UTC, viktoriiahdev commented on src/sass/layout/_products.scss
> +    transition: transform box-shadow 250ms $cubic;
А що з бордером не вийшло?

2022-04-11 13:55 UTC, AnnaKhanina commented on src/sass/layout/_products.scss
> +    transition: transform box-shadow 250ms $cubic;
дякую, зробила

2022-04-11 13:57 UTC, viktoriiahdev approved these changes

2022-04-11 13:57 UTC, merged